services:
  db-test:
    image: postgres:17
    container_name: db-test
    environment:
      - POSTGRES_DB=mydb_test 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init-test-data.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: backend
    environment:
      - DB_URL=jdbc:postgresql://db-test:5432/mydb_test
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      db-test:
        condition: service_healthy

  # Opcjonalny kontener tylko do Unit Test√≥w
  frontend-vitest:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.test
      target: unit-tests
    container_name: frontend-vitest